# contriever databrick
CUDA_VISIBLE_DEVICES=4 python ./scripts/train/retriever/train.py \
--full_dataset_file_path /local2/data/shared/rqa/training/databricks_400.pkl \
--train_file /local2/data/shared/rqa/training/databricks_new/train_w_q.jsonl \
--eval_file /local2/data/shared/rqa/training/databricks_new/eval_w_q.jsonl \
--model_name_or_path facebook/contriever-msmarco \
--do_train True \
--do_eval True \
--learning_rate 1e-4 \
--per_device_train_batch_size 256 \
--per_device_eval_batch_size 128 \
--search_algo inner_product \
--hard_neg_ratio 0.05 \
--contrastive_loss inbatch_contrastive \
--metric_for_best_model eval_retr/document_recall/recall \
--max_steps 200 \
--eval_steps 5 \
--save_steps 5 \
--logging_steps 1 \
--temperature 0.05 \
--output_dir result/model_checkpoints/contriever/contriever-ms_1e4_databricks_inbatch256_chunk400_fulldoc_temp0.05_hard0.05_train