CUDA_VISIBLE_DEVICES=2 python scripts/train/qa_llm/train_w_gt.py \
--use_flash_attention true \
--per_device_train_batch_size 4 \
--per_device_eval_batch_size 4 \
--deepspeed scripts/train/ds_config.json \
--learning_rate 1e-5 \
--gradient_accumulation_steps 2 \
--bf16 true \
--model_name_or_path lmsys/vicuna-7b-v1.5 \
--embedding_model intfloat/e5-base \
--embedding_max_num_to_retrieve 2 \
--num_train_epochs 3 \  # debugging
--logging_steps 10 \
--eval_steps 50 \
--save_steps 50 \
--output_dir model_checkpoints/debug \
--run_group debug